name: happy_color
description: Color-by-number prototype in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/my_feed/
    - assets/icons/library/
    - assets/icons/more/
    - assets/icons/feed/
    - assets/illustrations/
    - assets/pictures/fox/
    - assets/pictures/animals/animals_1/
    - assets/pictures/animals/animals_2/
    - assets/pictures/animals/animals_3/
    - assets/pictures/animals/animals_4/
    - assets/pictures/animals/animals_5/
    - assets/pictures/animals/animals_6/
    - assets/pictures/animals/animals_7/
    - assets/pictures/animals/animals_8/
    - assets/pictures/nature/nature_1/
    - assets/pictures/nature/nature_2/
    - assets/pictures/nature/nature_3/
    - assets/pictures/nature/nature_4/
    - assets/pictures/nature/nature_5/
    - assets/pictures/nature/nature_6/
    - assets/pictures/nature/nature_7/
    - assets/pictures/nature/nature_8/
    - assets/pictures/fantasy/fantasy_1/
    - assets/pictures/fantasy/fantasy_2/
    - assets/pictures/fantasy/fantasy_3/
    - assets/pictures/fantasy/fantasy_4/
    - assets/pictures/fantasy/fantasy_5/
    - assets/pictures/fantasy/fantasy_6/
    - assets/pictures/fantasy/fantasy_7/
    - assets/pictures/fantasy/fantasy_8/
    - assets/pictures/food/food_1/
    - assets/pictures/food/food_2/
    - assets/pictures/food/food_3/
    - assets/pictures/food/food_4/
    - assets/pictures/food/food_5/
    - assets/pictures/food/food_6/
    - assets/pictures/food/food_7/
    - assets/pictures/food/food_8/
    - assets/pictures/cities/cities_1/
    - assets/pictures/cities/cities_2/
    - assets/pictures/cities/cities_3/
    - assets/pictures/cities/cities_4/
    - assets/pictures/cities/cities_5/
    - assets/pictures/cities/cities_6/
    - assets/pictures/cities/cities_7/
    - assets/pictures/cities/cities_8/
    - assets/banners/
  shaders:
    - shaders/coloring.frag
