name: happy_color
description: Color-by-number prototype in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/artwork.png
    - assets/picture.json
    - assets/icons/my_feed/
    - assets/icons/library/
    - assets/icons/more/
    - assets/icons/feed/
    - assets/illustrations/
