import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:happy_color/core/theme/app_colors.dart';
import 'package:happy_color/features/coloring/presentation/pages/coloring_page.dart';
import 'package:happy_color/features/library/presentation/pages/library_page.dart';
import 'package:happy_color/features/my_feed/presentation/pages/my_feed_page.dart';
import 'package:happy_color/features/navigation/domain/entities/app_tab.dart';
import 'package:happy_color/features/navigation/presentation/providers/selected_tab_provider.dart';
import 'package:happy_color/features/navigation/presentation/widgets/app_tab_bar.dart';

class HomeShell extends ConsumerWidget {
  const HomeShell({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final tab = ref.watch(selectedTabProvider);
    return Scaffold(
      backgroundColor: AppColors.background,
      extendBody: true,
      body: IndexedStack(
        index: tab.index,
        children: [
          for (final tab in AppTab.values)
            switch (tab) {
              AppTab.myFeed => const MyFeedPage(),
              AppTab.library => const LibraryPage(),
              // Temporary: test picture generated by tools/generate_picture.py.
              AppTab.more => const ColoringPage(
                assetDir: 'assets/pictures/cities/cities_1',
              ),
            },
        ],
      ),
      bottomNavigationBar: const AppTabBar(),
    );
  }
}
